#################################################################################################
## Description: TCL script to get FPGA architecture from vivado                                ##
##                                                                                             ##
## Created by: Najdet Charaf                                                                   ##
#################################################################################################

# Please change the file name so that it is identical to the file which was generated by the getFPGA proc
# Default ./Misc/FPGA_part_{board_part}.arch
set fpga_info $otherDir/FPGA_part_${board_part}.arch

# an array that contains all clock region names
set clk_re_names [list ]

# create a dictionary for all clock region and their hard cores 
set clk_re_with_IPs [dict create ]

# an array that contains all information about every pkgpin/clock_region
set main_info [dict create]

# an array that contains all clk related tiles for each clock region which is important for the assignment of PartitionPins of clock signal
set clk_re_with_clk_tiles [dict create]

# Start with sorting, editing and saving (start with SES)
if {[file exists $fpga_info]} {
    
    startSES $fpga_info

} else {
   set errMsg "\n ERROR: No valid information file found.\n"
   error $errMsg
}
